### ISSUE TITLE
Zookeeper not ready

### ISSUE THREAD

**Issue by Aleks-Ya** [parrot-stream/docker-hive#3]
Hi! 
Try to use 1.2.2 version (updated to compose v3).
HiveServer2 doesn't start. I see "Zookeeper not ready! Exiting..." in log and then the app got stuck.

Log:
![image](https://user-images.githubusercontent.com/4932373/29271492-64cebaf8-8104-11e7-87da-84828ce0628e.png)

Docker version:
![image](https://user-images.githubusercontent.com/4932373/29271559-c175ebdc-8104-11e7-8a2e-6108bfb8e1f4.png)

**Comment by mcapitanio** [comment]
Hi,

that is because Hive has Zookeeper as external link. You can download
Zookeeper as well and start it before starting Hive.

Matteo

Il 14 ago 2017 2:30 PM, "Aleksey Yablokov" <notifications@github.com> ha
scritto:

**Comment by Aleks-Ya** [comment]
It's a surprize) 
Is Zookeeper the single external element required to run this image? 
Could you enumerate all such dependencies in [README](https://github.com/parrot-stream/docker-hive/blob/1.2.2/README.md)?

**Comment by mcapitanio** [comment]
Sure,
I'll do that in the README.
I could also change the docker-compose.yml to set Zookeeper as a link
dependency in such a way that it could be directly downloaded from the
Docker Hub without the need to clone the Zookeeper project and start the
docker from there.

Anyway Hive depends also on Postgres and Hadoop.
You can see all dependencies in the docker-compose.yml file:

external_links:
  - hadoop
  - zookeeper
  - postgres


2017-08-15 16:44 GMT+02:00 Aleksey Yablokov <notifications@github.com>:

**Comment by emonmishra** [comment]
I still get this error even when zookeeper service is running in another container. port 2181 of container is mapped to host 2181
